### PR TITLE
Update viewer to support zipped pdb files

### PR DESCRIPTION
**Pull request by rpartridge**
Update io.js to recognize if the pdb file being called is in gzipped format (ends in .gz). If so, use the Zlib library to decompress the data into a format that can be recognized and displayed, first converting the zipped file into an array of bytes that can be read by the Zlib decompress function.

Zlib: https://github.com/imaya/zlib.js

### CODE REVIEW

**Comment by biasmv** [comment]
Hi Rachel,

Thanks, for the PR. 

To be honest, I have been very reluctant to add support for gzipped PDB file reading. In my opinion, deflate/inflate of gzipped files is best handled by the browser directly as part of the HTTP protocol. If you have access to the server, you can instruct it to zip content before it's send over the wire. There is no JS involved in this.

I'm also reluctant to add the whole zlib js file to standard PV, since the zlib file is ~12kb of content that needs to be downloaded by everyone. I'd rather prefer to not have a dependency on this by default. Instead, I'd prefer to add a blob to the documentation that explains how this can be implemented by people that require this functionality. 

What do you think?

Best,
Marco

**Comment by rpartridge** [comment]
Hi Marco,


I see what you're saying about unzipping files in the browser; however, the reason I made these changes to PV was because in my specific case that didn't seem to be working, and the only way I was able to display gzipped PDB files was by editing io.js itself. I do agree that the zlib file is fairly bulky and it's probably best not to have a dependency on it though. I would be happy to add to the documentation to explain this implementation, if you think that would work the best.


Thanks and let me know!


Best,


Rachel Partridge
B.S. Candidate in Computer Science
School of Engineering and Applied Science
Washington University in St. Louis
________________________________

**Comment by biasmv** [comment]
Hi Rachel,

I certainly see your point as well. It might not always be possible to modify the web server to serve gzipped PDB files. Since it's possible to load gzipped files without having to modify any of the PV source, I'd prefer to just document how this can be achieved by combining functionality from PV and zlib. It would be fantastic if you could write a paragraph or two that show how this can be accomplished.

Best,
Marco

**Comment by rpartridge** [comment]
Hi Marco,


Sorry for the delayed response. Attached is the documentation I have written for using Zlib to unzip PDB files. Let me know if I should modify it or if I can do anything else to help.


Thanks!


Rachel Partridge
B.S. Candidate in Computer Science
School of Engineering and Applied Science
Washington University in St. Louis
________________________________

**Comment by biasmv** [comment]
No worries.

I don't see anything attached. You can send me the changes via e-mail and I'll incorporate them. Simplest would if you could directly send a diff of the change and open a new PR. The PR should be based on current master, so that there are no conflicts. 

Best,
Marco

**Pull request closed without merging**
