### PR TITLE
touch event calls click function

### PR DESCRIPTION
**Pull request by ajfarkas**
Single touch event on enabled devices calls the `opts.click` function. Double-touch still calls the double-click function, but does not also call the `opts.click` function again.

### CODE REVIEW

**Comment by biasmv** [comment]
Thanks for the PR. I'll test the changes over the next few days and let you know.

**Comment by biasmv** [comment]
Took me a while to get back to this. Could you rebase the PR onto master without checking in the minified JS? The minified JS conflicts with the version in master. I'll then test it on iOS.

Thanks!

**Comment by ajfarkas** [comment]
ok, finally got around to rebasing this.

**Comment by biasmv** [comment]
Thanks! Merged into master with a few minor tweaks. Runs fine on iOS. Haven't tested on Android, since I don't have an android phone with me.

**Pull request merged**
